#+OPTIONS: toc:nil num:nil
{:title  "Resume"
 :layout :page
 :navbar? true
 :tags   ["resume" "experience"]}

* Justin Good
  :LOGBOOK:
  CLOCK: [2019-10-09 Wed 10:46]--[2019-10-09 Wed 11:03] =>  0:17
  :END:
** Info
- justin@jgood.io
- https://jgood.io
- https://github.com/jgoodhcg
- https://www.linkedin.com/in/jgoodhcg
- Grand Rapids, Michigan
** Experience
*** Full Stack Developer, Gordon Food Service
/2018-05-14--Present/
- Implemented ci/cd + git ops with Jenkins, k8s, and github
- Launched React Native (expo) app with a Kotlin + Spring Boot backend
- Integrated app with legacy services 
- Onboarded several developers to the project
*** Software Dev Contractor, Tek Systems
/2017-05-11--2018-05-14/
- Developed green field content management solution for targeted advertising to customers
- Fixed bugs, added features and modules to a Drupal CMS site for internal company news and communication
*** Web Developer, One Stop Inc
/2016-02-18--2017-05-19/
- Created an isolated, reproducible, build script for production and development
- Maintained and extended e-commerce php app and supporting applications
*** IT Intern, City of Wyoming
/2015-5-19--2015-11-13/
- Developed CRUD web app for internal use
- Introduced version control to small dev team
** Side Projects
*** Time Align Mobile
/2018-05-12--present/  

https://github.com/jgoodhcg/time-align-mobile  

A native app using Expo, React Native, and shadow-cljs.
This is a passion project where I explore visual design and architectural design in an app that I /really/ use.

** Education
*** B.S. in Computer Science, Grand Valley State University
/2012--2015/
** Favorite Tech
*** Clojure(script)
Data driven, immutable, mostly pure functions, and *simple*.
After [[https://www.infoq.com/presentations/Simple-Made-Easy][simple made easy]] I was curious. 
Then after [[https://github.com/Day8/re-frame][the re-frame readme]] I was hooked.
*** Docker 
Containerized environments are easier to work with.
*** Spacemacs
Slowly realizing my life could run in org mode.
   
